CREATE TABLE Endereco
(
    Id INT NOT NULL,
    Origem VARCHAR(30) NOT NULL,
    Logradouro VARCHAR(100) NOT NULL,
    Cep VARCHAR(8) NOT NULL,
    Complemento VARCHAR(30),
    Bairro VARCHAR(50),
    Cidade VARCHAR(50),
    Uf VARCHAR(2),
    
    PRIMARY KEY (Id, Origem)
);

CREATE TABLE Filial
(
    Id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Nome VARCHAR(100) NOT NULL,
    Cnpj VARCHAR(15) NOT NULL,
    Matriz BOOLEAN NOT NULL,
    Ativo BOOLEAN NOT NULL DEFAULT TRUE,
    DataCadastro DATE NOT NULL
);

CREATE TABLE Perfil
(
    Id INT NOT NULL PRIMARY KEY,
    Nome VARCHAR(30) NOT NULL
);

CREATE TABLE Usuario
(
    Id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IdPerfil INT NOT NULL,
    IdFilial INT NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Login VARCHAR(50) NOT NULL UNIQUE,
    Senha VARCHAR(200) NOT NULL,
    Ativo BOOLEAN NOT NULL,
    DataCadastro DATE NOT NULL,
    
    FOREIGN KEY (IdPerfil) REFERENCES Perfil(Id),
    FOREIGN KEY (IdFilial) REFERENCES Filial(Id)
);

CREATE TABLE Colecao
(
    Id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Nome VARCHAR(100) NOT NULL,
    Periodo VARCHAR(50),
    Ano INT NOT NULL,
    Ativo BOOLEAN NOT NULL,
    DataCadastro DATE NOT NULL
);

CREATE TABLE Produto
(
    Id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1734, INCREMENT BY 1),
    Codigo VARCHAR(10) NOT NULL UNIQUE,
    Nome VARCHAR(50) NOT NULL,
    Descricao VARCHAR(150),
    IdColecao INT NOT NULL,
    Tipo VARCHAR(20) NOT NULL,
    Cor VARCHAR(50) NOT NULL,
    ValorProducao DECIMAL(14, 2) NOT NULL,
    ValorVenda DECIMAL(14, 2) NOT NULL,
    Ativo BOOLEAN NOT NULL,
    DataCadastro DATE NOT NULL,

    FOREIGN KEY (IdColecao) REFERENCES Colecao(Id)
);

CREATE TABLE Estoque
(
    Id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IdProduto INT NOT NULL,
    IdFilial INT NOT NULL,
    Tamanho VARCHAR(3) NOT NULL,
    Quantidade INT NOT NULL,
    
    FOREIGN KEY (IdProduto) REFERENCES Produto(Id),
    FOREIGN KEY (IdFilial) REFERENCES Filial(ID)
);

CREATE TABLE Cliente
(
    Id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Nome VARCHAR(50) NOT NULL,
    Cpf VARCHAR(11) NOT NULL,
    Sexo VARCHAR(10) NOT NULL,
    DataNascimento DATE NOT NULL,
    Ativo BOOLEAN NOT NULL,
    DataCadastro DATE NOT NULL
);

CREATE TABLE Venda
(
    Id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IdCliente BIGINT NOT NULL,
    IdUsuario INT NOT NULL,
    Valor DECIMAL(14, 2) NOT NULL,
    DataVenda DATE NOT NULL,

    FOREIGN KEY (IdCliente) REFERENCES Cliente(Id),
    FOREIGN KEY (IdUsuario) REFERENCES Usuario(Id)
);

CREATE TABLE VendaItem
(
    Id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IdVenda BIGINT NOT NULL,
    IdProduto INT NOT NULL,
    Tamanho VARCHAR(3) NOT NULL,
    Quantidade INT NOT NULL,

    FOREIGN KEY (IdVenda) REFERENCES Venda(Id),
    FOREIGN KEY (IdProduto) REFERENCES Produto(Id)
);

CREATE TABLE Menu
(
    Id INT NOT NULL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Caminho VARCHAR(50)
);

CREATE TABLE MenuPerfil
(
    IdMenu INT NOT NULL,
    IdPerfil INT NOT NULL,

    FOREIGN KEY (IdMenu) REFERENCES Menu(Id),
    FOREIGN KEY (IdPerfil) REFERENCES Perfil(Id)
);
